apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/*.log
    output.elasticsearch:
      hosts: ["your-elasticsearch-host:9200"]
