apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.2
        volumeMounts:
        - name: filebeat-config
          mountPath: /home/cloudshell-user/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: filebeat-logs
          mountPath: /home/cloudshell-user/filebeat/filebeat.yml
      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: filebeat-logs
        emptyDir: {}
